### ISSUE TITLE
h264转mp4报错

### ISSUE THREAD

**Issue by sunkingsss** [chn-lee-yumi/ffmpeg_on_browser#1]
[h264 @ 0x1037390] Error splitting the input into NAL units.
[h264 @ 0x1037390] error while decoding MB 29 61, bytestream -6
[h264 @ 0x1037390] concealing 5732 DC, 5732 AC, 5732 MV errors in P frame
[mpeg @ 0x1036070] start time for stream 1 is not set in estimate_timings_from_pts
[mpeg @ 0x1036070] Could not find codec parameters for stream 1 (Audio: mp2, 0 channels): unspecified frame size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpeg, from '/input/test.h264':
  Duration: 00:00:09.46, start: 0.000000, bitrate: 2012 kb/s
    Stream #0:0[0x1e0]: Video: h264 (High), yuvj420p(pc, bt470bg/bt470bg/bt709), 2688x1520, 25.08 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x1c0]: Audio: mp2, 0 channels
[h264 @ 0x24a6370] Warning: not compiled with thread support, using thread emulation
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mpeg4 (native))
Press [q] to stop, [?] for help
[h264 @ 0x24a6370] no frame!
Error while decoding stream #0:0: Invalid data found when processing input
[h264 @ 0x24a6370] no frame!
Error while decoding stream #0:0: Invalid data found when processing input

大佬，您好，能不能将h264转为fmp4?

**Comment by chn-lee-yumi** [comment]
视频能否发一下？

**Comment by sunkingsss** [comment]
[test.h264.zip](https://github.com/chn-lee-yumi/ffmpeg_on_browser/files/5472505/test.h264.zip)
您好，麻烦帮忙看下

**Comment by chn-lee-yumi** [comment]
你好，已更新ffmpeg版本。我测试是没问题的，但是浏览器兼容性稍差，chrome可以用，其它浏览器不保证。你可以打开 https://chn-lee-yumi.github.io/ffmpeg_on_browser/ 测试一下。

**Comment by sunkingsss** [comment]
您好，确实可以正常转了，谢谢。但是这个转码速度有点太慢了，我测试了一下，转码3.2M的测试文件大概用了2分30秒，您觉得这个能优化吗？我之前还想在网页上使用ffmpg去做实时视频流的转码，如果难以优化的话，那这个方案得丢弃掉了

**Comment by chn-lee-yumi** [comment]
这个我需要时间测试一下

**Comment by sunkingsss** [comment]
好的，谢谢

**Comment by chn-lee-yumi** [comment]
你好，因为暂时没有办法实现多线程，目前转码速度受限于单线程和wasm的效率。所以目前恐怕没有办法做到实时视频流的转码。

**Comment by sunkingsss** [comment]
好的，十分感谢
